import { FlatCompat } from "@eslint/eslintrc";
import { dirname } from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
    baseDirectory: __dirname,
});

const eslintConfig = [
    {
        ignores: [
            ".next/**",
            "out/**",
            "coverage/**",
            "node_modules/**",
            "dist/**",
            "build/**",
            "**/*.config.ts",
            "**/*.config.mjs",
            "**/*.config.js",
            "next-env.d.ts", // Generated by Next.js
            "public/funnel-system/**", // Vanilla JS editor from genie-v1
            "resources/**", // Local resources
            "docs/reference-design/**", // Reference design from Lovable
            "OLD-APPDOCS-ONLY-REFERENCE/**", // Old reference docs that shouldn't be linted or compiled
        ],
    },
    ...compat.extends("next/core-web-vitals", "next/typescript"),
    {
        rules: {
            "@typescript-eslint/no-unused-vars": [
                "warn",
                {
                    argsIgnorePattern: "^_",
                    varsIgnorePattern: "^_",
                },
            ],
            "@typescript-eslint/no-explicit-any": "warn",
            "react/no-unescaped-entities": "off",
        },
    },
    // Relax rules for test files
    {
        files: [
            "**/__tests__/**",
            "**/*.test.ts",
            "**/*.test.tsx",
            "**/*.spec.ts",
            "**/*.spec.tsx",
        ],
        rules: {
            "@typescript-eslint/no-explicit-any": "off",
            "@next/next/no-img-element": "off", // Allow <img> in test mocks
        },
    },
];

export default eslintConfig;

