/**
 * ESLint Configuration
 *
 * Uses native flat config with eslint-config-next for Next.js 16+
 * This approach avoids the FlatCompat circular reference issues with ESLint 9
 */
import { createRequire } from "module";

const require = createRequire(import.meta.url);

// Load eslint-config-next which already provides flat config arrays
const nextConfig = require("eslint-config-next/core-web-vitals");
const nextTypescriptConfig = require("eslint-config-next/typescript");

const eslintConfig = [
    {
        ignores: [
            ".next/**",
            "out/**",
            "coverage/**",
            "node_modules/**",
            "dist/**",
            "build/**",
            "**/*.config.ts",
            "**/*.config.mjs",
            "**/*.config.js",
            "next-env.d.ts", // Generated by Next.js
            "public/funnel-system/**", // Vanilla JS editor from genie-v1
            "resources/**", // Local resources
            "docs/reference-design/**", // Reference design from Lovable
            "OLD-APPDOCS-ONLY-REFERENCE/**", // Old reference docs that shouldn't be linted or compiled
            ".gitworktrees/**", // Git worktrees - separate branches
            ".swarm/**", // Swarm temporary files
        ],
    },
    // Next.js core-web-vitals and TypeScript configs (flat config format)
    ...nextConfig,
    ...nextTypescriptConfig,
    // Custom rules
    {
        rules: {
            "@typescript-eslint/no-unused-vars": [
                "warn",
                {
                    argsIgnorePattern: "^_",
                    varsIgnorePattern: "^_",
                },
            ],
            "@typescript-eslint/no-explicit-any": "warn",
            "react/no-unescaped-entities": "off",
        },
    },
    // Relax rules for test files
    {
        files: [
            "**/__tests__/**",
            "**/*.test.ts",
            "**/*.test.tsx",
            "**/*.spec.ts",
            "**/*.spec.tsx",
        ],
        rules: {
            "@typescript-eslint/no-explicit-any": "off",
            "@next/next/no-img-element": "off", // Allow <img> in test mocks
        },
    },
];

export default eslintConfig;

